guard :rspec, cmd: 'bundle exec rspec --color --format=documentation' do
	watch(%r{^spec/.+_spec\.rb$}) #whenever a _spec.rb file changes, run guard
	watch(%r{^lib/(.+)\.rb$}) { |m| "spec/#{m[1]}_spec.rb" }
	watch("app.rb") {|m| "spec/app_spec.rb"}
end