# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2772933fb242e119a0be2df920ab5d3f89dfadc6d3b8f92927fe620eeeb977f68d16a8cbdf9e320daae7b556996387c3ce2515e7caf5d2c69a77c0ed786c8373

test:
  secret_key_base: a13de19f84842d9ccee49944e26527f19184d5b4da65de07a63d42b7ed3b0b59a151b7d6f8adf89215e559ac2ec60429549f728a50959f7a31784d0a213bcca6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
