# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bf70c8e5e2066594b637940f186613d22e9ae438a434a9a9db75a757e2b4162d4445a84cd2d17b42a66716de16e26b40e7f66d06a659968f1f510c1e38dfaee

test:
  secret_key_base: 0c1d7071fa95ca0545e13e9f77d575d7692e1a3a8fb553c68cd0d3369113c67984c3466d69fe3acdc1c2adb53234eea94c9d08b57fb83eb4d21fa33cf61cdea1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
